# Generated by Django 5.2.1 on 2026-06-25 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=180)),
                ('first_name', models.CharField(blank=True, max_length=90)),
                ('last_name', models.CharField(blank=True, max_length=90)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=90)),
                ('service', models.CharField(max_length=180)),
                ('requirement', models.TextField()),
                ('page', models.CharField(blank=True, max_length=220)),
                ('page_url', models.URLField(blank=True, max_length=700)),
                ('source', models.CharField(default='Website', max_length=140)),
                ('status', models.CharField(choices=[('New Lead', 'New Lead'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Quotation Sent', 'Quotation Sent'), ('Follow-up', 'Follow-up'), ('Converted', 'Converted'), ('Closed/Lost', 'Closed/Lost')], db_index=True, default='New Lead', max_length=40)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], db_index=True, default='Normal', max_length=20)),
                ('shortlisted', models.BooleanField(db_index=True, default=False)),
                ('lead_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('next_follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('converted_to_job_card_id', models.CharField(blank=True, max_length=120)),
                ('follow_up_count', models.PositiveIntegerField(default=0)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=160)),
                ('utm_medium', models.CharField(blank=True, max_length=160)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('utm_term', models.CharField(blank=True, max_length=160)),
                ('utm_content', models.CharField(blank=True, max_length=160)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'shortlisted'], name='website_web_status_a55568_idx'), models.Index(fields=['service', 'submitted_at'], name='website_web_service_d809ef_idx'), models.Index(fields=['lead_score', 'submitted_at'], name='website_web_lead_sc_79275e_idx')],
            },
        ),
    ]
