# Generated by Django 5.2.1 on 2026-06-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=220)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(db_index=True, max_length=140)),
                ('uid', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('original_name', models.CharField(max_length=240)),
                ('stored_name', models.CharField(max_length=240)),
                ('file', models.FileField(upload_to='uploads/complaints/%Y/%m/')),
                ('mime_type', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=80)),
                ('job_card_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('file_name', models.CharField(max_length=180)),
                ('company_sent', models.BooleanField(default=False)),
                ('client_sent', models.BooleanField(default=False)),
                ('audit_saved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(db_index=True, max_length=80)),
                ('document_id', models.CharField(max_length=190)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['collection', '-updated_at'],
                'indexes': [models.Index(fields=['collection', 'document_id'], name='portal_admi_collect_eac513_idx'), models.Index(fields=['collection', 'updated_at'], name='portal_admi_collect_1d258e_idx')],
                'constraints': [models.UniqueConstraint(fields=('collection', 'document_id'), name='unique_portal_document')],
            },
        ),
        migrations.CreateModel(
            name='PortalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('uid', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=180)),
                ('client_name', models.CharField(blank=True, max_length=180)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('page_url', models.URLField(blank=True, max_length=700)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='portal_admi_event_t_930cf1_idx'), models.Index(fields=['reference', 'created_at'], name='portal_admi_referen_32f532_idx'), models.Index(fields=['client_email', 'created_at'], name='portal_admi_client__5484d1_idx')],
            },
        ),
    ]
